configmap:
  data:
    conf:
      env-prefix: "NITROCI"
    data-availability:
      sequencer-inbox-address: "0x6c97864CE4bEf387dE0b3310A44230f7E3F1be0D"
      local-file-storage:
        enable: true
        data-dir: "/data"
      key:
        key-dir: "/secret/key"
        
    enable-rpc: true

dasecretName: "ci-secret-nitro"

overrideKeydirMountPath: "/dummy/path"

extraEnv:
  - name: NITROCI_DATA__AVAILABILITY_PARENT__CHAIN__NODE__URL
    valueFrom:
      secretKeyRef:
        name: ci-secret-nitro
        key: PARENT_CHAIN_URL_SEPOLIA

extraVolumes:
  - name: privkeyvolume
    secret:
      secretName: ci-secret-nitro

extraVolumeMounts:
  - name: privkeyvolume
    mountPath: /secret/key/das_bls
    readOnly: true
    subPath: priv-key

ci:
  secretManifest:
    enabled: true
  secrets:
    priv-key: "YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
