{{- if .Values.validator.enabled  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nitro.fullname" . }}-validator
  labels:
    {{- include "nitro.labels" . | nindent 4 }}
data:
  config.json: |
  {{- if  and .Values.validator.configmap  .Values.validator.configmap.data }}
    {{- .Values.validator.configmap.data | toRawJson | nindent 4 }}
  {{- end }} 
  
{{- end }}
