{{- if .Values.validator.enabled }}
{{- range .Values.validator.splitvalidator.deployments }}
{{- $global := deepCopy $.Values.validator.splitvalidator.global }}
{{- $deployment := . }}
{{- $mergedValues := merge $global $deployment }}
{{- if $mergedValues.keda.enabled }}
{{- with $mergedValues.keda.scaledObject }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "nitro.fullname" $ }}-val-{{ $deployment.name }}
  labels:
    {{- include "nitro.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    deploymentName: {{ include "nitro.fullname" $ }}-val-{{ $deployment.name }}
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
