{{- if .Values.validator.enabled }}
{{- range .Values.validator.splitvalidator.deployments }}
{{- $global := deepCopy $.Values.validator.splitvalidator.global }}
{{- $deployment := . }}
{{- $mergedValues := merge $global $deployment }}
{{- if $mergedValues.keda.enabled }}
{{- $scaledObject := deepCopy $mergedValues.keda.scaledObject }}
{{- range $index, $trigger := $scaledObject.triggers }}
{{- if eq $trigger.type "prometheus" }}
{{- $trigger := set $trigger "metadata" (deepCopy $trigger.metadata) }}
{{- if $trigger.metadata.queryTemplate }}
{{- $query := tpl $trigger.metadata.queryTemplate (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "Template" $.Template "deployment" $deployment) }}
{{- $_ := set $trigger.metadata "query" $query }}
{{- $_ := unset $trigger.metadata "queryTemplate" }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "nitro.fullname" $ }}-val-{{ $deployment.name }}
  labels:
    {{- include "nitro.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "nitro.fullname" $ }}-val-{{ $deployment.name }}
  {{- $scaledObject | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
