{{- if .Values.validator.enabled }}
{{- range .Values.validator.splitvalidator.deployments }}
{{- $global := deepCopy $.Values.validator.splitvalidator.global }}
{{- $deployment := . }}
{{- $mergedValues := merge $global $deployment }}
{{- $pdbEnabled := $mergedValues.pdb.enabled | default $.Values.validator.splitvalidator.global.pdb.enabled }}
{{- if $pdbEnabled }}
{{- $labels := include "nitro.labels" $ }}
{{- $selectorLabels := include "nitro.selectorLabels" $ }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nitro.fullname" $ }}-val-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- $rc := int (.replicas | default $mergedValues.replicaCount) }}
  {{- if and (eq $rc 1) (not $mergedValues.pdb.minAvailable) (not $mergedValues.pdb.maxUnavailable) }}
  maxUnavailable: "100%"
  {{- else if and ($mergedValues.pdb.minAvailable) (not $mergedValues.pdb.maxUnavailable) }}
  minAvailable: {{ $mergedValues.pdb.minAvailable }}
  {{- else if and ($mergedValues.pdb.maxUnavailable) (not $mergedValues.pdb.minAvailable) }}
  maxUnavailable: {{ $mergedValues.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      validator: {{ .name | quote }}
      function: split-validator
{{- end }}
{{- end }}
{{- end }}
