{{- if and $.Values.validator.enabled $.Values.validator.statefulset.serviceMonitor.enabled }}
{{- $fullName := include "nitro.fullname" . }}
{{- $labels := include "nitro.labels" . }}
{{- $selectorLabels := include "nitro.selectorLabels" .}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}-validator
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      function: arb-validator
  endpoints:
    - port: {{ .Values.validator.serviceMonitor.portName | default "http" }}
      {{- if .Values.validator.serviceMonitor.interval }}
      interval: {{ .Values.validator.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.validator.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.validator.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.validator.serviceMonitor.path }}
      path: {{ .Values.validator.serviceMonitor.path }}
      {{- end }}
      {{- if .Values.validator.serviceMonitor.scheme }}
      scheme: {{ .Values.validator.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.validator.serviceMonitor.tlsConfig }}
      tlsConfig: 
        {{- toYaml .Values.validator.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- with .Values.validator.serviceMonitor.relabelings }}
      relabelings: {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
