{{- if .Values.validator.enabled }}
{{- $fullName := include "nitro.fullname" . }}
{{- $labels := include "nitro.labels" . }}
{{- $selectorLabels := include "nitro.selectorLabels" .}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-validator
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  {{- if $.Values.validator.statefulset.auth.enabled }}
    - port: {{ $.Values.validator.statefulset.auth.port }}
      targetPort: {{ $.Values.validator.statefulset.auth.port }}
      protocol: TCP
      name: auth
  {{- end }}
  {{- if .Values.validator.configmap.data.metrics }}
    - port: {{ index .Values "validator" "configmap" "data" "metrics-server" "port" }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  {{- range .Values.validator.statefulset.extraPorts }}
  {{- if .serviceEnabled | default true }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    function: arb-validator
{{- end }}
