{{- if .Values.validator.enabled }}
{{- range .Values.validator.splitvalidator.deployments }}
{{- $global := deepCopy $.Values.validator.splitvalidator.global }}
{{- $deployment := . }}
{{- $mergedValues := merge $global $deployment }}
{{- $serviceMonitorEnabled := $mergedValues.serviceMonitor.enabled | default $.Values.validator.splitvalidator.global.serviceMonitor.enabled }}
{{- if $serviceMonitorEnabled }}
{{- $labels := include "nitro.labels" $ }}
{{- $selectorLabels := include "nitro.selectorLabels" $ }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Chart.Name }}-val-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      validator: {{ .name }}
      function: split-validator
  endpoints:
    - port: {{ $mergedValues.serviceMonitor.portName | default "http" }}
      {{- if $mergedValues.serviceMonitor.interval }}
      interval: {{ $mergedValues.serviceMonitor.interval }}
      {{- end }}
      {{- if $mergedValues.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $mergedValues.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if $mergedValues.serviceMonitor.path }}
      path: {{ $mergedValues.serviceMonitor.path }}
      {{- end }}
      {{- if $mergedValues.serviceMonitor.scheme }}
      scheme: {{ $mergedValues.serviceMonitor.scheme }}
      {{- end }}
      {{- if $mergedValues.serviceMonitor.tlsConfig }}
      tlsConfig: 
        {{- toYaml $mergedValues.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- with $mergedValues.serviceMonitor.relabelings }}
      relabelings: {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
