{{- if .Values.headlessservice.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nitro.fullname" . }}-headless
  labels:
    {{- include "nitro.labels" . | nindent 4 }}
  annotations:
    {{- if $.Values.headlessservice.annotations }}
    {{- toYaml $.Values.headlessservice.annotations | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  clusterIPs:
  - None
  selector:
    {{- include "nitro.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: {{ .Values.headlessservice.publishNotReadyAddresses }}
{{- end }}

