apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nitro.fullname" . }}
  labels:
    {{- include "nitro.labels" . | nindent 4 }}
  annotations:
    nitro.arbitrum.io/desiredReplicas: {{ $.Values.replicaCount | quote }}
spec:
  serviceName: "{{ include "nitro.fullname" . }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nitro.selectorLabels" . | nindent 6 }}
  podManagementPolicy: Parallel
  {{- if .Values.updateStrategy }}
  {{- with .Values.updateStrategy }}
  updateStrategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.wallet.files }}
        checksum/wallets: {{ include (print $.Template.BasePath "/wallets.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nitro.selectorLabels" . | nindent 8 }}
        function: nitro
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nitro.serviceAccountName" . }}
      securityContext:
        {{- with .Values.podSecurityContext }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
        {{- include "nitro.initContainers" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.diagnosticMode }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              #!/usr/bin/env bash
              set -eo pipefail

              trap 'exit 0' SIGTERM

              sleep infinity &
              wait $!
          {{- else if .Values.commandOverride.enabled }}
          {{- with .Values.commandOverride.command }}
          command: {{- toYaml . | nindent 8}}
          {{- end }}
          {{- with .Values.commandOverride.args }}
          args: {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- else }}
          command: [/usr/local/bin/nitro]
          args:
            {{- if .Values.configmap.data.metrics}}
            - --metrics
            {{- end }}
            {{- if .Values.configmap.enabled }}
            - --conf.file=/config/config.json
            {{- end }}
            {{- if .Values.customArgs }}
            {{- include "nitro.customArgs" . | nindent 12 }}
            {{- end }}
          ports:
            {{- if and .Values.configmap.data.http .Values.configmap.data.http.port}}
            - name: http-rpc
              containerPort: {{ .Values.configmap.data.http.port }}
              protocol: TCP
            {{- end }}
            {{- if and .Values.configmap.data.ws .Values.configmap.data.ws.port }}
            - name: ws
              containerPort: {{ .Values.configmap.data.ws.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.configmap.data.metrics }}
            - name: metrics
              containerPort: {{ index .Values "configmap" "data" "metrics-server" "port" }}
              protocol: TCP
            {{- end }}
            {{- if .Values.configmap.data.pprof }}
            - name: pprof
              containerPort: {{ index .Values "configmap" "data" "pprof-cfg" "port" }}
              protocol: TCP
            {{- end }}
            {{- if and .Values.configmap.data.node .Values.configmap.data.node.feed .Values.configmap.data.node.feed.output .Values.configmap.data.node.feed.output.port }}
            - name: feed
              containerPort: {{ .Values.configmap.data.node.feed.output.port }}
              protocol: TCP
            {{- end }}
            {{- range .Values.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if and .Values.livenessProbe.exec (kindIs "string" .Values.livenessProbe.exec.command) }}
            {{- omit .Values.livenessProbe "enabled" "exec" | toYaml | nindent 12 }}
            exec:
              command:
                {{- tpl .Values.livenessProbe.exec.command . | nindent 14 }}
            {{- else }}
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if and .Values.startupProbe.enabled .Values.configmap.data.http .Values.configmap.data.http.port }}
          startupProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  {{- include "startupProbe" . | nindent 18 }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          {{- end }}
          {{- end }}
          env:
          {{- include "nitro.env" . | nindent 12 }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
          {{- if .Values.jwtSecret.enabled }}
          - name: jwt-secret
            mountPath: /secrets/jwtsecret
            subPath: jwtSecret
            readOnly: true
          {{- end }}
          - name: nitrodata
            mountPath: {{ .Values.configmap.data.persistent.chain }}
          {{- end }}
          {{- if .Values.blobPersistence.enabled }}
          - name: nitroblobdata
            mountPath: {{ index .Values "configmap" "data" "parent-chain" "blob-client" "blob-directory" }}
          {{- end }}
          {{- if .Values.configmap.enabled }}
          - name: config
            mountPath: /config/
          {{- end }}
          {{- if .Values.wallet.files }}
          {{ range $filename, $json := .Values.wallet.files }}
          - name: wallet-files
            mountPath: {{ $.Values.wallet.mountPath }}{{ $filename }}
            subPath: {{ $filename }}
          {{- end }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10}}
          {{- end }}
          {{- range .Values.additionalVolumeClaims }}
          {{- if .enabled }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- include "nitro.sidecars" . | nindent 8 }}
      volumes:
      {{- if .Values.jwtSecret.enabled }}
      - name: jwt-secret
        secret:
          secretName: {{ include "nitro.fullname" . }}-jwt
      {{- end }}
      {{- if .Values.configmap.enabled }}
      - name: config
        configMap:
          name: {{ include "nitro.fullname" . }}
      {{- end }}
      {{- if .Values.wallet.files }}
      - name: wallet-files
        secret:
          secretName: {{ include "nitro.fullname" . }}-wallets
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- range .Values.additionalVolumeClaims }}
      {{- if .enabled }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .Values.validator.enabled }}
      nodeSelector:
        {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.validator.splitvalidator.global.nodeSelector | nindent 8 }}
        {{- end }}
      {{- else if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 600 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "nitro.selectorLabels" $ | nindent 12 }}
            function: nitro
        {{- end }}
        {{- end }}
      {{- end }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: nitrodata
        {{- with .Values.storageAnnotations }}
        annotations:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          app: {{ template "nitro.name" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
          {{- if .Values.persistence.snapshotValue }}
          snapshot: {{ .Values.persistence.snapshotValue }}
          {{- end }}
      spec:
        accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- end }}
      {{- if .Values.blobPersistence.enabled }}
    - metadata:
        name: nitroblobdata
        {{- with .Values.storageAnnotations }}
        annotations:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          app: {{ template "nitro.name" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec: 
        accessModes:
        {{- toYaml .Values.blobPersistence.accessModes | nindent 8 }}
        {{- if .Values.blobPersistence.storageClassName }}
        storageClassName: {{ .Values.blobPersistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.blobPersistence.size | quote }}
      {{- end }}
