{{- if .Values.ci.secretManifest.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "ci-secret-nitro"
type: Opaque
data:
  {{- range $key, $value := .Values.ci.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
