apiVersion: v1
kind: Service
metadata:
  name: {{ include "das.fullname" . }}
  labels:
    {{- include "das.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if index .Values.configmap.data "enable-rpc" }}
    - port: {{ index .Values.configmap.data "rpc-port" }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    {{- end }}
    {{- if index .Values.configmap.data "enable-rest" }}
    - port: {{ index .Values.configmap.data "rest-port" }}
      targetPort: http-rest
      protocol: TCP
      name: http-rest
    {{- end }}
    {{- if index .Values.configmap.data "metrics" }}
    - port: {{ index .Values.configmap.data "metrics-server" "port" }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "das.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
