{{- if .Values.auctioneer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "timeboost.serviceAccountName" . }}-auctioneer
  labels:
    {{- include "timeboost.labels" . | nindent 4 }}
  {{- with .Values.auctioneer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
