apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timeboost.fullname" . }}-bid-validator
  labels:
    {{- include "timeboost.labels" . | nindent 4 }}
  annotations:
    timeboost.arbitrum.io/desiredReplicas: {{ $.Values.auctioneer.replicaCount | quote }}
spec:
  {{- if not .Values.auctioneer.autoscaling.enabled }}
  replicas: {{ .Values.auctioneer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "timeboost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/bid-validator-cm.yaml") . | sha256sum }}
        {{- with .Values.auctioneer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "timeboost.selectorLabels" . | nindent 8 }}
        function: nitro
        {{- with .Values.auctioneer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.auctioneer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "timeboost.serviceAccountName" . }}
      securityContext:
        {{- with .Values.auctioneer.podSecurityContext }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.auctioneer.priorityClassName }}
      priorityClassName: {{ .Values.auctioneer.priorityClassName }}
      {{- end }}
      initContainers:
        {{- if .Values.auctioneer.initContainers }}
        {{- toYaml .Values.auctioneer.initContainers | nindent 8 }}
        {{- end }}
        {{- include "timeboost.initContainers" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.auctioneer.securityContext | nindent 12 }}
          image: "{{ .Values.auctioneer.image.repository }}:{{ .Values.auctioneer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auctioneer.image.pullPolicy }}
          {{- if .Values.auctioneer.diagnosticMode }}
          command: ["sleep"]
          args: ["infinity"]
          {{- else if .Values.auctioneer.commandOverride.enabled }}
          {{- with .Values.auctioneer.commandOverride.command }}
          command: {{- toYaml . | nindent 8}}
          {{- end }}
          {{- with .Values.auctioneer.commandOverride.args }}
          args: {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- else }}
          command: [/usr/local/bin/nitro]
          args:
            {{- if .Values.auctioneer.configmap.data.metrics}}
            - --metrics
            {{- end }}
            {{- if .Values.auctioneer.configmap.enabled }}
            - --conf.file=/config/config.json
            {{- end }}
            {{- if .Values.auctioneer.customArgs }}
            {{- include "timeboost.customArgs" . | nindent 12 }}
            {{- end }}
          ports:
            {{- if and .Values.auctioneer.configmap.data.http .Values.auctioneer.configmap.data.http.port}}
            - name: http-rpc
              containerPort: {{ .Values.auctioneer.configmap.data.http.port }}
              protocol: TCP
            {{- end }}
            {{- if and .Values.auctioneer.configmap.data.ws .Values.auctioneer.configmap.data.ws.port }}
            - name: ws
              containerPort: {{ .Values.auctioneer.configmap.data.ws.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.auctioneer.configmap.data.metrics }}
            - name: metrics
              containerPort: {{ index .Values.auctioneer."configmap" "data" "metrics-server" "port" }}
              protocol: TCP
            {{- end }}
            {{- if .Values.auctioneer.configmap.data.pprof }}
            - name: pprof
              containerPort: {{ index .Values.auctioneer."configmap" "data" "pprof-cfg" "port" }}
              protocol: TCP
            {{- end }}
            {{- range .Values.auctioneer.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- if .Values.auctioneer.livenessProbe.enabled }}
          livenessProbe:
            {{- if and .Values.auctioneer.livenessProbe.exec (kindIs "string" .Values.auctioneer.livenessProbe.exec.command) }}
            {{- omit .Values.auctioneer.livenessProbe "enabled" "exec" | toYaml | nindent 12 }}
            exec:
              command:
                {{- tpl .Values.auctioneer.livenessProbe.exec.command . | nindent 14 }}
            {{- else }}
            {{- omit .Values.auctioneer.livenessProbe "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.auctioneer.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.auctioneer.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if and .Values.auctioneer.startupProbe.enabled .Values.auctioneer.configmap.data.http .Values.auctioneer.configmap.data.http.port }}
          startupProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  {{- include "startupProbe" . | nindent 18 }}
            failureThreshold: {{ .Values.auctioneer.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.auctioneer.startupProbe.periodSeconds }}
          {{- end }}
          {{- end }}
          env:
          {{- include "timeboost.env" . | nindent 12 }}
          {{- with .Values.auctioneer.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.auctioneer.persistence.enabled }}
          volumeMounts:
          {{- if .Values.auctioneer.configmap.enabled }}
          - name: config
            mountPath: /config/
          {{- end }}
          {{- if .Values.auctioneer.extraVolumeMounts }}
          {{- toYaml .Values.auctioneer.extraVolumeMounts | nindent 10}}
          {{- end }}
          {{- range .Values.auctioneer.additionalVolumeClaims }}
          {{- if .enabled }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }} 
          resources:
            {{- toYaml .Values.auctioneer.resources | nindent 12 }}
        {{- include "timeboost.sidecars" . | nindent 8 }}
      volumes:
      {{- if .Values.auctioneer.jwtSecret.enabled }}
      - name: jwt-secret
        secret:
          secretName: {{ include "timeboost.fullname" . }}-jwt
      {{- end }}
      {{- if .Values.auctioneer.configmap.enabled }}
      - name: config
        configMap:
          name: {{ include "timeboost.fullname" . }}
      {{- end }}
      {{- if .Values.auctioneer.wallet.files }}
      - name: wallet-files
        secret:
          secretName: {{ include "timeboost.fullname" . }}-wallets
      {{- end }}
      {{- if .Values.auctioneer.extraVolumes }}
      {{- toYaml .Values.auctioneer.extraVolumes | nindent 6 }}
      {{- end }}
      {{- range .Values.auctioneer.additionalVolumeClaims }}
      {{- if .enabled }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .Values.auctioneer.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.auctioneer.nodeSelector | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.auctioneer.terminationGracePeriodSeconds | default 600 }}
      {{- with .Values.auctioneer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auctioneer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auctioneer.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "timeboost.selectorLabels" $ | nindent 12 }}
            function: nitro
        {{- end }}
        {{- end }}
      {{- end }}
