{{- if .Values.bidValidator.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timeboost.fullname" . }}-bid-validator
  labels:
    {{- include "timeboost.bidValidator.labels" . | nindent 4 }}
data:
  config.json: |
    {{- include "timeboost.bidValidator.configProcessor" . | nindent 4 }}
{{- end }}
