{{- if .Values.bidValidator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "timeboost.serviceAccountName" . }}
  labels:
    {{- include "timeboost.labels" . | nindent 4 }}
  {{- with .Values.bidValidator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
