{
 "title": "Arbitrum Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Regex", "query": ".*" },
   {
    "name": "sequencerjob",
    "label": "Sequencer Jobs",
    "query": {
     "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\"},job)"
    }
   },
   {
    "name": "nitronodejob",
    "label": "Nitro Node Jobs",
    "query": {
     "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\"},job)"
    }
   },
   {
    "name": "relayjob",
    "label": "Relay Jobs",
    "query": {
     "query": "label_values(arb_feed_clients_connect{namespace=~\"$namespacepattern\"},job)"
    }
   },
   {
    "name": "validatorjob",
    "label": "Validator Jobs",
    "query": {
     "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator Summary [$validatorjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "validatorjob",
   "collapsed": true,
   "panels": [
    {
     "title": "Validation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(arb_validator_last_block_validated{namespace=~\"$namespacepattern\",job=\"$validatorjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(arb_validator_msg_count_validated{namespace=~\"$namespacepattern\",job=\"$validatorjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Validator Block Backlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(arb_validator_msg_count_current_batch{namespace=~\"$namespacepattern\",job=\"$validatorjob\"} - arb_validator_msg_count_validated{namespace=~\"$namespacepattern\",job=\"$validatorjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(arb_validator_last_block_in_last_batch{namespace=~\"$namespacepattern\",job=\"$validatorjob\"} - arb_validator_last_block_validated{namespace=~\"$namespacepattern\",job=\"$validatorjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequencer Summary [$sequencerjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "sequencerjob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$sequencerjob SendRawTransaction Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_success_count{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_success_count{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}-Conditional"
      }
     ]
    },
    {
     "title": "$sequencerjob SendRawTransaction Failure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_failure_count{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_failure_count{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}-Conditional"
      }
     ]
    },
    {
     "title": "$sequencerjob SendRawTransaction Success Duration p9999",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rpc_duration_eth_sendRawTransaction_success{namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rpc_duration_eth_sendRawTransactionConditional_success{namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod)",
       "legendFormat": "{{pod}}-Conditional"
      }
     ]
    },
    {
     "title": "$sequencerjob  SendRawTransaction Failure Duration p9999",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rpc_duration_eth_sendRawTransaction_failure{namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "rpc_duration_eth_sendRawTransactionConditional_failure{namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}",
       "legendFormat": "{{pod}}-Conditional"
      }
     ]
    },
    {
     "title": "$sequencerjob Gas Used Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(arb_gas_used{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval]))by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Sequence Number Confirmation Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(arb_sequencenumber_latest{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"} - arb_sequencenumber_confirmed{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Backlog Without NonceFailureCache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(arb_sequencer_backlog{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"} - arb_sequencer_noncefailurecache_size{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequencer Detail [$sequencerjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "sequencerjob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$sequencerjob NonceFailureCache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(arb_sequencer_noncefailurecache_size{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Sequencer Version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by(image) (kube_pod_container_info{namespace=~\"$namespacepattern\", pod=~\"$sequencerjob.*\", image=~\".*/nitro-node:.*\"})",
       "legendFormat": "{{image}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(chain_head_block{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(arb_sequencer_active{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Block Range",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max(chain_head_block{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) - min(chain_head_block{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"})",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "$sequencerjob Nonce Failure Cache Overflow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(arb_sequencer_noncefailurecache_overflow{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Block Creation time p9999",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(arb_sequencer_block_creation{namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$sequencerjob Feed Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(arb_feed_clients_connected{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(arb_feed_clients_current{namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$sequencerjob Storage R/W Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespacepattern\", pod=~\"$sequencerjob-.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}-R"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespacepattern\", pod=~\"$sequencerjob-.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}-W"
      }
     ]
    }
   ]
  },
  {
   "title": "Relays Summary [$relayjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "relayjob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$relayjob Total Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(arb_feed_clients_current{namespace=~\"$namespacepattern\",job=\"$relayjob\"})",
       "legendFormat": "Connections"
      },
      {
       "expr": "sum(arb_feed_clients_connected{namespace=~\"$namespacepattern.*\",job=\"$relayjob\"})",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "$relayjob Confirmation Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "arb_sequencenumber_latest{namespace=~\"$namespacepattern\",job=\"$relayjob\"} - arb_sequencenumber_confirmed{namespace=~\"$namespacepattern\",job=\"$relayjob\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$relayjob relay cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\", image!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespacepattern\", pod=~\"$relayjob-[0-9a-f].*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespacepattern\", pod=~\"$relayjob-[0-9a-f].*\", resource=\"cpu\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "$relayjob relay mem usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Relays Detail [$relayjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "relayjob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$relayjob Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "arb_feed_clients_current{namespace=~\"$namespacepattern\", job=\"$relayjob\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "arb_feed_clients_connected{namespace=~\"$namespacepattern\", job=\"$relayjob\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$relayjob Sources Connected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "arb_feed_sources_connected{namespace=~\"$namespacepattern\", job=\"$relayjob\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$relayjob Range",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max(arb_sequencenumber_latest{namespace=~\"$namespacepattern\", job=\"$relayjob\"}) - min(arb_sequencenumber_latest{namespace=~\"$namespacepattern\", job=\"$relayjob\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$relayjob Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(arb_sequencenumber_latest{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$relayjob Connect/Disconnect Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(arb_feed_clients_connect{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval]))",
       "legendFormat": "connect"
      },
      {
       "expr": "sum(rate(arb_feed_clients_disconnect{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval]))",
       "legendFormat": "disconnect"
      }
     ]
    },
    {
     "title": "$relayjob Connection Limit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(arb_feed_clients_limited{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval]))",
       "legendFormat": "limited"
      }
     ]
    },
    {
     "title": "$relayjob Feed Clients Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(arb_feed_clients_duration{namespace=~\"$namespacepattern\",job=\"$relayjob\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$relayjob Total Transmit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespacepattern\", pod=~\"$relayjob.*\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "$relayjob Out of Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(irate(arb_feed_clients_failed_worker{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$relayjob Feed Clients Cached Messages Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(arb_feed_clients_cache_sent{namespace=~\"$namespacepattern\", job=\"$relayjob\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$relayjob Failed WS Upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(irate(arb_feed_clients_failed_upgrade{namespace=~\"$namespacepattern\", job=\"$relayjob\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$relayjob Version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "sum by(image) (kube_pod_container_info{namespace=~\"$namespacepattern\",pod=~\"$relayjob.*\",image=~\".*/nitro-node:.*\"})",
       "legendFormat": "{{image}}"
      },
      {
       "expr": "sum by(image) (kube_pod_container_info{namespace=~\"$namespacepattern.*\",pod=~\"$relayjob.*\",image=~\".*/arb-relay:.*\"})",
       "legendFormat": "{{image}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nitro Node RPC Summary [$nitronodejob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "nitronodejob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$nitronodejob RPC Methods - success",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(rpc_duration_arb_getAggregator_success_count{namespace=~\"$namespacepattern\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "arb_getAggregator"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_accounts_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_accounts"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_blockNumber_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_blockNumber"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_call_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_call"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_chainId_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_chainId"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_estimateGas_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_estimateGas"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_gasPrice_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_gasPrice"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getBalance_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getBalance"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getBlockByHash_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getBlockByHash"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getBlockByNumber_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getBlockByNumber"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getCode_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getCode"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getFilterChanges_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getFilterChanges"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getFilterLogs_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getFilterLogs"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getLogs_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getLogs"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getStorageAt_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getStorageAt"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getTransactionByHash_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getTransactionByHash"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getTransactionCount_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getTransactionCount"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getTransactionReceipt_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getTransactionReceipt"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_newBlockFilter_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_newBlockFilter"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_newFilter_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_newFilter"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_sendRawTransaction"
      },
      {
       "expr": "sum(rate(rpc_duration_net_version_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "net_version"
      },
      {
       "expr": "sum(rate(rpc_duration_web3_clientVersion_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "web3_clientVersion"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_sendRawTransactionConditional"
      }
     ]
    },
    {
     "title": "$nitronodejob RPC Methods - Failure",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "sendRawTransaction"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getTransactionCount_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getTransactionCount"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_gasPrice_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_gasPrice"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendTransaction_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_sendTransaction"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getLogs_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getLogs"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getFilterChanges_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getFilterChanges"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getStorageAt_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getStorageAt"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getFilterLogs_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getFilterLogs"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getCode_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getCode"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getBlockByNumber_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "eth_getBlockByNumber"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_call_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))\n",
       "legendFormat": "eth_call"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_getBalance_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))\n",
       "legendFormat": "eth_getBalance"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_estimateGas_failure_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))\n",
       "legendFormat": "eth_estimateGas"
      },
      {
       "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_success_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))\n",
       "legendFormat": "eth_sendRawTransactionConditional"
      }
     ]
    },
    {
     "title": "$nitronodejob RPC Total Req/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_duration_all_count{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval]))",
       "legendFormat": "Req/s"
      }
     ]
    },
    {
     "title": "$nitronodejob Block Number Range",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "max(chain_head_block{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) - min(chain_head_block{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"})"
      }
     ]
    },
    {
     "title": "$nitronodejob CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespacepattern.*\", pod=~\"${nitronodejob}-[0-9a-f].*\", image!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespacepattern.*\", pod=~\"${nitonodejob}-[0-9a-f].*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespacepattern.*\", pod=~\"${nitronodejob}-[0-9a-f].*\", resource=\"cpu\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "$nitronodejob Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\",container!=\"\",resource=\"memory\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\",resource=\"memory\"})",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Nitro Node RPC Requests Detail [$nitronodejob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "nitronodejob",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$nitronodejob RPC Methods Success - p9999 latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(rpc_duration_arb_getAggregator_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_arb_getAggregator_success"
      },
      {
       "expr": "max(rpc_duration_eth_blockNumber_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_blockNumber_success"
      },
      {
       "expr": "max(rpc_duration_eth_call_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_call_success"
      },
      {
       "expr": "max(rpc_duration_eth_chainId_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_chainId_success"
      },
      {
       "expr": "max(rpc_duration_eth_estimateGas_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_estimateGas_success"
      },
      {
       "expr": "max(rpc_duration_eth_gasPrice_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_gasPrice_success"
      },
      {
       "expr": "max(rpc_duration_eth_getBalance_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBalance_success"
      },
      {
       "expr": "max(rpc_duration_eth_getBlockByHash_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBlockByHash_success"
      },
      {
       "expr": "max(rpc_duration_eth_getBlockByNumber_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBlockByNumber_success"
      },
      {
       "expr": "max(rpc_duration_eth_getCode_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getCode_success"
      },
      {
       "expr": "max(rpc_duration_eth_getFilterChanges_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getFilterChanges_success"
      },
      {
       "expr": "max(rpc_duration_eth_getFilterLogs_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getFilterLogs_success"
      },
      {
       "expr": "max(rpc_duration_eth_getLogs_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getLogs_success"
      },
      {
       "expr": "max(rpc_duration_eth_getStorageAt_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getStorageAt_success"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionByHash_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionByHash_success"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionCount_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionCount_success"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionReceipt_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionReceipt_success"
      },
      {
       "expr": "max(rpc_duration_eth_newBlockFilter_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_newBlockFilter_success"
      },
      {
       "expr": "max(rpc_duration_eth_newFilter_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_newFilter_success"
      },
      {
       "expr": "max(rpc_duration_eth_sendRawTransaction_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_sendRawTransaction_success"
      },
      {
       "expr": "max(rpc_duration_net_version_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_net_version_success"
      },
      {
       "expr": "max(rpc_duration_web3_clientVersion_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_web3_clientVersion_success"
      }
     ]
    },
    {
     "title": "$nitronodejob RPC Methods Failure - p9999 latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(rpc_duration_arb_getAggregator_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_arb_getAggregator_failure"
      },
      {
       "expr": "max(rpc_duration_eth_blockNumber_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_blockNumber_failure"
      },
      {
       "expr": "max(rpc_duration_eth_call_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_call_failure"
      },
      {
       "expr": "max(rpc_duration_eth_chainId_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_chainId_failure"
      },
      {
       "expr": "max(rpc_duration_eth_estimateGas_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_estimateGas_failure"
      },
      {
       "expr": "max(rpc_duration_eth_gasPrice_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_gasPrice_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getBalance_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBalance_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getBlockByHash_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBlockByHash_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getBlockByNumber_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getBlockByNumber_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getCode_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getCode_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getFilterChanges_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getFilterChanges_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getFilterLogs_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getFilterLogs_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getLogs_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getLogs_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getStorageAt_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getStorageAt_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionByHash_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionByHash_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionCount_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionCount_failure"
      },
      {
       "expr": "max(rpc_duration_eth_getTransactionReceipt_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_getTransactionReceipt_failure"
      },
      {
       "expr": "max(rpc_duration_eth_newBlockFilter_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_newBlockFilter_failure"
      },
      {
       "expr": "max(rpc_duration_eth_newFilter_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_newFilter_failure"
      },
      {
       "expr": "max(rpc_duration_eth_sendRawTransaction_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_eth_sendRawTransaction_failure"
      },
      {
       "expr": "max(rpc_duration_net_version_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_net_version_failure"
      },
      {
       "expr": "max(rpc_duration_web3_clientVersion_failure{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile='0.9999'})",
       "legendFormat": "rpc_duration_web3_clientVersion_failure"
      }
     ]
    },
    {
     "title": "$nitronodejob Sequence Number Range",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "max(arb_sequencenumber_latest{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) - min(arb_sequencenumber_latest{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"})"
      }
     ]
    },
    {
     "title": "$nitronodejob Eth Call by Quantile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(rpc_duration_eth_call_success{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$nitronodejob Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(chain_head_block{namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "$nitronodejob Version",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by(image) (kube_pod_container_info{namespace=~\"$namespacepattern.*\",pod=~\"${nitronodejob}[-0-9]*|${nitronodejob}-[a-z0-9]*-[a-z0-9]*\",image=~\".*/nitro-node:.*|.*/load-balancer:.*\"})",
       "legendFormat": "{{image}}"
      }
     ]
    }
   ]
  },
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "README",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "This dashboard is intended for use with Abitrum installations using https://github.com/OffchainLabs/community-helm-charts as it expects naming patterns from those charts.\n\nFor each variable select all jobs that are applicable. For example the validator job should be selected as a `Validator Job` job and as a `Nitro Node Job`\n\n"
     }
    }
   ]
  }
 ]
}