{
 "title": "Nitro Node Detail",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "nitronodejob",
    "label": "Nitro Node Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$nitronodejob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$nitronodejob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nitro Node RPC Requests Detail [$nitronodejob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "nitronodejob"
  },
  {
   "title": "RPC Methods success - p9999 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max(rpc_duration_arb_getAggregator_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_arb_getAggregator_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_blockNumber_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_blockNumber_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_call_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_call_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_chainId_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_chainId_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_estimateGas_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_estimateGas_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_gasPrice_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_gasPrice_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBalance_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBalance_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBlockByHash_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBlockByHash_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBlockByNumber_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBlockByNumber_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getCode_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getCode_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getFilterChanges_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getFilterChanges_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getFilterLogs_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getFilterLogs_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getLogs_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getLogs_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getStorageAt_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getStorageAt_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionByHash_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionByHash_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionCount_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionCount_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionReceipt_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionReceipt_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_newBlockFilter_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_newBlockFilter_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_newFilter_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_newFilter_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_sendRawTransaction_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_sendRawTransaction_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_net_version_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_net_version_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_timeboost_sendExpressLaneTransaction_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_timeboost_sendExpressLaneTransaction_success - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_web3_clientVersion_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_web3_clientVersion_success - {{cluster}}"
    }
   ]
  },
  {
   "title": "RPC Methods failure - p9999 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max(rpc_duration_arb_getAggregator_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_arb_getAggregator_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_blockNumber_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_blockNumber_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_call_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_call_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_chainId_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_chainId_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_estimateGas_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_estimateGas_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_gasPrice_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_gasPrice_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBalance_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBalance_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBlockByHash_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBlockByHash_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getBlockByNumber_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getBlockByNumber_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getCode_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getCode_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getFilterChanges_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getFilterChanges_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getFilterLogs_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getFilterLogs_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getLogs_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getLogs_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getStorageAt_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getStorageAt_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionByHash_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionByHash_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionCount_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionCount_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_getTransactionReceipt_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_getTransactionReceipt_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_newBlockFilter_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_newBlockFilter_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_newFilter_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_newFilter_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_sendRawTransaction_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_eth_sendRawTransaction_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_net_version_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_net_version_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_timeboost_sendExpressLaneTransaction_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_timeboost_sendExpressLaneTransaction_failure - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_web3_clientVersion_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\", quantile=\"0.9999\"}) by (cluster)",
     "legendFormat": "rpc_duration_web3_clientVersion_failure - {{cluster}}"
    }
   ]
  },
  {
   "title": "Sequence Number Range",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(arb_sequencenumber_latest{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) - min(arb_sequencenumber_latest{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Eth Call by Quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "max(rpc_duration_eth_call_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) by (quantile, cluster)",
     "legendFormat": "{{quantile}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by(image, cluster) (kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",pod=~\"${nitronodejob}[-0-9]*|${nitronodejob}-[a-z0-9]*-[a-z0-9]*\",image=~\".*/nitro-node:.*|.*/load-balancer:.*\"})",
     "legendFormat": "{{image}} - {{cluster}}"
    }
   ]
  }
 ]
}