{
 "title": "Nitro Node RPC Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "nitronodejob",
    "label": "Nitro Node Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$nitronodejob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$nitronodejob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nitro Node RPC Summary [$nitronodejob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "nitronodejob"
  },
  {
   "title": "RPC Methods - Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rpc_duration_arb_getAggregator_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "arb_getAggregator - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_blockNumber_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_blockNumber - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_call_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_call - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_chainId_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_chainId - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_estimateGas_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_estimateGas - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_gasPrice_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_gasPrice - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBalance_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBalance - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBlockByHash_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBlockByHash - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBlockByNumber_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBlockByNumber - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getCode_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getCode - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getFilterChanges_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getFilterChanges - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getFilterLogs_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getFilterLogs - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getLogs_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getLogs - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getStorageAt_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getStorageAt - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionByHash_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionByHash - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionCount_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionCount - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionReceipt_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionReceipt - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_newBlockFilter_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_newBlockFilter - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_newFilter_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_newFilter - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_sendRawTransaction - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_net_version_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "net_version - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_timeboost_sendExpressLaneTransaction_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "timeboost_sendExpressLaneTransaction - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_web3_clientVersion_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "web3_clientVersion - {{cluster}}"
    }
   ]
  },
  {
   "title": "RPC Methods - Failure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rpc_duration_arb_getAggregator_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "arb_getAggregator - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_blockNumber_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_blockNumber - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_call_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_call - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_chainId_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_chainId - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_estimateGas_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_estimateGas - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_gasPrice_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_gasPrice - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBalance_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBalance - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBlockByHash_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBlockByHash - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getBlockByNumber_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getBlockByNumber - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getCode_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getCode - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getFilterChanges_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getFilterChanges - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getFilterLogs_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getFilterLogs - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getLogs_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getLogs - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getStorageAt_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getStorageAt - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionByHash_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionByHash - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionCount_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionCount - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_getTransactionReceipt_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_getTransactionReceipt - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_newBlockFilter_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_newBlockFilter - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_newFilter_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_newFilter - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "eth_sendRawTransaction - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_net_version_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "net_version - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_timeboost_sendExpressLaneTransaction_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "timeboost_sendExpressLaneTransaction - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_web3_clientVersion_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "web3_clientVersion - {{cluster}}"
    }
   ]
  },
  {
   "title": "RPC Total Req/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_duration_all_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Req/s - {{cluster}}"
    }
   ]
  },
  {
   "title": "Block Number Range",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "max(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"}) - min(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$nitronodejob\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\", pod=~\"${nitronodejob}-[0-9a-f].*\", image!=\"\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\", pod=~\"${nitronodejob}-[0-9a-f].*\", container=~\".*nitro.*|.*lb.*\", resource=\"cpu\"}) by (cluster)",
     "legendFormat": "Limit - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\", pod=~\"${nitronodejob}-[0-9a-f].*\", container=~\".*nitro.*|.*lb.*\", resource=\"cpu\"}) by (cluster)",
     "legendFormat": "Request - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\", container!=\"\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\", container=~\".*nitro.*|.*lb.*\", resource=\"memory\"}) by (cluster)",
     "legendFormat": "Limit - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",pod=~\"$nitronodejob-[0-9a-f].*\", container=~\".*nitro.*|.*lb.*\", resource=\"memory\"}) by (cluster)",
     "legendFormat": "Request - {{cluster}}"
    }
   ]
  }
 ]
}