{
 "title": "Relays Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "relayjob",
    "label": "Relay Jobs",
    "query": "label_values(arb_feed_clients_connect{namespace=~\"$namespacepattern\", cluster=~\"$cluster\", pod=~\".*relay.*|.*feed.*\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(arb_feed_clients_connect{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$relayjob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(arb_feed_clients_connect{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$relayjob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Relays Summary [$relayjob]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "relayjob" },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(arb_feed_clients_current{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$relayjob\"}) by (cluster)",
     "legendFormat": "Connections - {{cluster}}"
    },
    {
     "expr": "sum(arb_feed_clients_connected{cluster=~\"$cluster\",namespace=~\"$namespacepattern.*\",job=\"$relayjob\"}) by (cluster)",
     "legendFormat": "Connections - {{cluster}}"
    }
   ]
  },
  {
   "title": "Confirmation Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "arb_sequencenumber_latest{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$relayjob\"} - arb_sequencenumber_confirmed{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$relayjob\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\", image!=\"\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespacepattern\", pod=~\"$relayjob-[0-9a-f].*\", container=~\".*nitro.*|.*relay.*\", resource=\"cpu\"}) by (cluster)",
     "legendFormat": "Limit - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=~\"$namespacepattern\", pod=~\"$relayjob-[0-9a-f].*\", container=~\".*nitro.*|.*relay.*\", resource=\"cpu\"}) by (cluster)",
     "legendFormat": "Requests - {{cluster}}"
    }
   ]
  },
  {
   "title": "Feed Backlog Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(arb_feed_backlog_bytes{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$relayjob\"}) by(job, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespacepattern\", pod=~\"$relayjob-.*\", resource=\"memory\"}) by (cluster)",
     "legendFormat": "Limit - {{cluster}}"
    }
   ]
  }
 ]
}