{
 "title": "Sequencer Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "sequencerjob",
    "label": "Sequencer Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\", pod=~\".*seq.*\", pod!~\".*batch.*\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$sequencerjob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$sequencerjob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Coordinator Priorities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coordinator Priorities",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(coordinator, cluster) (multicluster_manager_coordinator_priorities{cluster=~\"$cluster\",namespace=~\"$namespacepattern\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Summary [$sequencerjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "sequencerjob"
  },
  {
   "title": "SendRawTransaction Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_success_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-Conditional"
    }
   ]
  },
  {
   "title": "SendRawTransaction Failure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransaction_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "sum(rate(rpc_duration_eth_sendRawTransactionConditional_failure_count{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-Conditional"
    }
   ]
  },
  {
   "title": "SendRawTransaction Success Duration p9999",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max(rpc_duration_eth_sendRawTransaction_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_sendRawTransactionConditional_success{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-Conditional"
    }
   ]
  },
  {
   "title": "SendRawTransaction Failure Duration p9999",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max(rpc_duration_eth_sendRawTransaction_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    },
    {
     "expr": "max(rpc_duration_eth_sendRawTransactionConditional_failure{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-Conditional"
    }
   ]
  },
  {
   "title": "Gas Used Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(arb_gas_used{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Sequence Number Confirmation Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(arb_sequencenumber_latest{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"} - arb_sequencenumber_confirmed{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Backlog Without NonceFailureCache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(arb_sequencer_backlog{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"} - arb_sequencer_noncefailurecache_size{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Current & Expected Surplus",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by(pod, chain) (arb_sequencer_currentsurplus{cluster=~\"$cluster\",namespace=~\"$namespacepattern\"}) and on(pod) (arb_sequencer_active{} == 1)",
     "legendFormat": "Current: {{chain}}"
    },
    {
     "expr": "sum by(pod, chain) (arb_sequencer_expectedsurplus{cluster=~\"$cluster\",namespace=~\"$namespacepattern\"}) and on (pod) (arb_sequencer_active{} == 1)",
     "legendFormat": "Expected: {{chain}}"
    }
   ]
  }
 ]
}