{
 "title": "Sequencer Detail",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "sequencerjob",
    "label": "Sequencer Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\", pod=~\".*seq.*\", pod!~\".*batch.*\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$sequencerjob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$sequencerjob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sequencer Detail [$sequencerjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "sequencerjob"
  },
  {
   "title": "NonceFailureCache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(arb_sequencer_noncefailurecache_size{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Sequencer Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(image, cluster) (kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",pod=~\"$sequencerjob.*\",image=~\".*/nitro-node:.*\"})",
     "legendFormat": "{{image}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(arb_sequencer_active{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Block Range",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) - min(chain_head_block{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"})",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Nonce Failure Cache Overflow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(arb_sequencer_noncefailurecache_overflow{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Block Creation time p9999",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(arb_sequencer_block_creation{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\",quantile=\"0.9999\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Feed Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum(arb_feed_clients_connected{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}} - Connected"
    },
    {
     "expr": "sum(arb_feed_clients_current{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}} - Current"
    }
   ]
  },
  {
   "title": "Storage R/W Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=~\"$cluster\",container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespacepattern\", pod=~\"$sequencerjob-.*\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-R"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$cluster\",container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespacepattern\", pod=~\"$sequencerjob-.*\"}[$__rate_interval])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}-W"
    }
   ]
  },
  {
   "title": "Current & Expected Surplus",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "sum by(pod, chain) (arb_sequencer_currentsurplus{cluster=~\"$cluster\",namespace=~\"$namespacepattern\"}) and on(pod) (arb_sequencer_active{} == 1)",
     "legendFormat": "Current: {{chain}}"
    },
    {
     "expr": "sum by(pod, chain) (arb_sequencer_expectedsurplus{cluster=~\"$cluster\",namespace=~\"$namespacepattern\"}) and on (pod) (arb_sequencer_active{} == 1)",
     "legendFormat": "Expected: {{chain}}"
    }
   ]
  },
  {
   "title": "Timeboost Auction Resolution Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(chain, cluster) (rate(arb_sequencer_timeboost_auctionresolution{cluster=~\"$cluster\",namespace=~\"$namespacepattern\",job=\"$sequencerjob\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - {{cluster}}-R"
    }
   ]
  }
 ]
}