{
 "title": "Redis Stream Validator Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "validatorjob",
    "label": "Validator Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\", pod=~\".*val.*\", job!~\".*current.*|.*timeboost.*\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$validatorjob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$validatorjob\", pod=~\"$pod\"}, pod)"
   },
   {
    "name": "redisstream",
    "query": "label_values(redis_stream_length{cluster=~\"$cluster\", namespace=~\"$namespacepattern\"},stream)"
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Stream Data [$redisstream]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "redisstream"
  },
  {
   "title": "Redis Entry Ages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(time()*1000) - redis_stream_last_entry_id{stream=\"$redisstream\", namespace=~\"$namespacepattern\"}",
     "legendFormat": "Last Entry Age"
    },
    {
     "expr": "(time()*1000) - redis_stream_first_entry_id{stream=\"$redisstream\", namespace=~\"$namespacepattern\"}",
     "legendFormat": "First Entry Age"
    }
   ]
  },
  {
   "title": "Redis Stream",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(redis_stream_length{stream=\"$redisstream\", namespace=~\"$namespacepattern\"}) by (pod)",
     "legendFormat": "Length {{pod}}"
    },
    {
     "expr": "sum(redis_stream_group_messages_pending{stream=\"$redisstream\", namespace=~\"$namespacepattern\"}) by (pod)",
     "legendFormat": "Messages Pending {{pod}}"
    },
    {
     "expr": "sum(redis_stream_group_lag{stream=\"$redisstream\", namespace=~\"$namespacepattern\"}) by (pod)",
     "legendFormat": "Lag {{pod}}"
    }
   ]
  },
  {
   "title": "Stream Id Tracking",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(time()*1000) - redis_stream_group_last_delivered_id{stream=\"$redisstream\", namespace=~\"$namespacepattern\"} >= 0",
     "legendFormat": "redis_stream_group_last_delivered_id"
    },
    {
     "expr": "(time()*1000) - redis_stream_last_entry_id{stream=\"$redisstream\", namespace=~\"$namespacepattern\"} >= 0",
     "legendFormat": "redis_stream_last_entry_id"
    },
    {
     "expr": "(time()*1000) - redis_stream_first_entry_id{stream=\"$redisstream\", namespace=~\"$namespacepattern\"} >= 0",
     "legendFormat": "redis_stream_first_entry_id"
    }
   ]
  },
  {
   "title": "Nitro Validator [$validatorjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "validatorjob"
  },
  {
   "title": "Number Of Workers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespacepattern\", deployment=~\"$validatorjob-val-.*\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Workers CPU Usage By Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$validatorjob-val-.*\", namespace=~\"$namespacepattern\", image!=\"\"} [1m])) by (container, pod)"
    }
   ]
  },
  {
   "title": "Validator profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(arb_validator_profile_wait_to_launch{job=~\"$validatorjob\", namespace=~\"$namespacepattern\", quantile=\"0.75\"})",
     "legendFormat": "wait_to_launch"
    },
    {
     "expr": "sum(arb_validator_profile_wait_to_record{job=~\"$validatorjob\", namespace=~\"$namespacepattern\", quantile=\"0.75\"})",
     "legendFormat": "wait_to_record"
    },
    {
     "expr": "sum(arb_validator_profile_recording{job=~\"$validatorjob\", namespace=~\"$namespacepattern\", quantile=\"0.75\"})",
     "legendFormat": "recording"
    },
    {
     "expr": "sum(arb_validator_profile_running{job=~\"$validatorjob\", namespace=~\"$namespacepattern\", quantile=\"0.75\"})",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Validation progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "arb_validator_msg_count_created{job=~\"$validatorjob\", namespace=~\"$namespacepattern\"} > 0",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "arb_validator_msg_count_record_sent{job=~\"$validatorjob\", namespace=~\"$namespacepattern\"} > 0",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "arb_validator_msg_count_validated{job=~\"$validatorjob\", namespace=~\"$namespacepattern\"} > 0",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "arb_validator_msg_count_last_validation_sent{job=~\"$validatorjob\", namespace=~\"$namespacepattern\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Validator Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(arb_inbox_latest_batch_message{namespace=~\"$namespacepattern\", job=~\"$validatorjob\"} - arb_validator_msg_count_validated{namespace=~\"$namespacepattern\", job=~\"$validatorjob\"}) by (job) > 0"
    }
   ]
  },
  {
   "title": "Workers CPU Usage Aggregate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$validatorjob-.*\", namespace=~\"$namespacepattern\", image!=\"\", container=\"nitro-stateless\"}[1m]))",
     "legendFormat": "{{$validatorjob}}"
    }
   ]
  }
 ]
}