{
 "title": "Validator Detail",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Source", "query": "prometheus" },
   { "name": "namespacepattern", "label": "Namespace Pattern" },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": "label_values(arb_feed_clients_current{namespace=~\"$namespacepattern\"}, cluster)"
   },
   {
    "name": "validatorjob",
    "label": "Validator Jobs",
    "query": "label_values(chain_head_block{namespace=~\"$namespacepattern\", cluster=~\"$cluster\", pod=~\".*val.*\", job!~\".*current.*|.*timeboost.*\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$validatorjob\"}, pod)"
   },
   {
    "name": "pod_controller",
    "label": "Pod Controller",
    "query": "label_values(chain_head_block{cluster=~\"$cluster\", namespace=~\"$namespacepattern\", job=~\"$validatorjob\", pod=~\"$pod\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Validator Detail [$validatorjob]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "validatorjob"
  },
  {
   "title": "Function Retries (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_runtime_retry{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Challenges Submitted (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_challenge_submitted{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Onchain Edge Creation Events (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_watcher_edge_added{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Confirmed Royal Edges (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_confirmed{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Subchallenges Added (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_layer_zero_leaves{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Bisected Royal Edges (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_bisected{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Confirmed Edges (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_watcher_confirmed_by_time{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "by time - {{pod}} - {{cluster}}"
    },
    {
     "expr": "sum(increase(arb_validator_watcher_confirmed_by_children{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "by children - {{pod}} - {{cluster}}"
    },
    {
     "expr": "sum(increase(arb_validator_watcher_confirmed_by_claim{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "by claim - {{pod}} - {{cluster}}"
    },
    {
     "expr": "sum(increase(arb_validator_watcher_confirmed_by_osp{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "by one step proof - {{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Edge Tracker Goroutines Spawned Gauge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum(arb_validator_tracker_spawned{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Evil Assertions Observed (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_evil_assertion{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Assertions Confirmed By Time (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_assertion_confirmed{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Assertions Posted (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_poster_assertion_posted{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "History Commitment In-Progress Cache Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum(arb_validator_inprogresscache_inflight{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}) by (pod, cluster)",
     "legendFormat": "Computed Requests"
    },
    {
     "expr": "sum(arb_validator_inprogresscache_pending{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}) by (pod, cluster)",
     "legendFormat": "Pending Requests"
    }
   ]
  },
  {
   "title": "Error Posting Assertion (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_poster_error_posting_assertion{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Execution Node Offline (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(arb_state_provider_execution_node_offline{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Error Confirming Assertion By Time (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_error_confirming_assertion_by_time{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Error Confirming Assertion By Winner (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_watcher_error_confirming_assertion_by_winner{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Evil Assertions Confirmed (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_evil_assertion_confirmed{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Error Confirming Edge By One Step Proof (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_error_confirming_edge_by_one_step_proof{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Onchain Timer Differed After Confirmation (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_onchain_timer_differed_after_confirmation_job{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Invalid Inclusion Proof (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_tracker_invalid_inclusion_proof{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Safe Block Delay (1h Sum)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(arb_validator_scanner_safe_block_delay{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}[1h])) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Chain Catching Up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "sum(arb_validator_poster_chain_catching_up{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}) by (pod, cluster)",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Latest Confirmed Assertion Block Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "arb_validator_scanner_latest_confirmed_assertion_block_number{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Sysload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "expr": "system_cpu_sysload{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Sysload Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "system_cpu_sysload_total{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Procload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "system_cpu_procload{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Procload Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "system_cpu_procload_total{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Schedule Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "expr": "system_cpu_schedlatency{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Syswait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "system_cpu_syswait{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Syswait Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "system_cpu_syswait_total{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "system_cpu_goroutines{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "expr": "system_cpu_threads{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "system_memory_allocs{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Pauses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "system_memory_pauses{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "system_memory_objects{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "targets": [
    {
     "expr": "system_memory_used{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Frees",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "system_memory_frees{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Held",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "system_memory_held{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Read Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "system_disk_readcount{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Read Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
   "targets": [
    {
     "expr": "system_disk_readdata{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Write Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "system_disk_writecount{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Write Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 61 },
   "targets": [
    {
     "expr": "system_disk_writedata{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "system_disk_readbytes{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 61 },
   "targets": [
    {
     "expr": "system_disk_writebytes{namespace=~\"$namespacepattern\",job=\"$validatorjob\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} - {{cluster}}"
    }
   ]
  }
 ]
}