{{- if .Values.headlessService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}-headless
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  clusterIPs:
  - None
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: {{ .Values.headlessService.publishNotReadyAddresses }}
{{- end }}
