name: Build & Push Updated Charts (MANUAL)

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the branch to checkout (e.g., main, develop)'
        required: true
        default: 'main'
      chart_dir:
        description: 'Directory of the chart to be pushed (e.g., charts/my-chart)'
        required: true
      chart_version:
        description: 'Version of the chart to be pushed (e.g., 1.2.3). Will be appended with -dev'
        required: true

permissions:
  contents: read

concurrency:
  group: push-charts-dev-${{ github.ref }}
  cancel-in-progress: false

jobs:
  push-charts:
    runs-on: ubuntu-4
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - uses: a-thomas-22/helm-push-action@v0.0.29
        env:
          PATHS: ${{ github.event.inputs.chart_dir }}
          VERSION: ${{ github.event.inputs.chart_version }}-dev 
          FORCE: "True"
          CHARTMUSEUM_URL: "chartmuseum-external.iue1v1-0.i.arbitrum-internal.io/public"
          CHARTMUSEUM_ALIAS: "chartmuseum.offchainlabs.internal"
          CHARTMUSEUM_CA_CERT: "${{ secrets.CHARTMUSEUM_CA_CERT }}"
          CHARTMUSEUM_KEY: "${{ secrets.CHARTMUSEUM_KEY }}"
          CHARTMUSEUM_CERT: "${{ secrets.CHARTMUSEUM_CERT }}"
