name: Build & Push Updated Charts (PROD)
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  get-modified-charts:
    runs-on: ubuntu-4
    outputs:
      paths: ${{ steps.get-modified-charts.outputs.paths }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Get modified charts
        id: get-modified-charts
        run: |
          paths=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep ^charts/ | cut -d/ -f1,2 | uniq | tr '\n' ' ')
          echo "paths=${paths}" >> $GITHUB_OUTPUT

  push-charts:
    needs: get-modified-charts
    runs-on: ubuntu-4
    if: ${{ needs.get-modified-charts.outputs.paths != '' }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # Create and push git tags
      - name: Create and push git tags
        run: |
          IFS=' ' read -ra ADDR <<< "${{ needs.get-modified-charts.outputs.paths }}"
          for path in "${ADDR[@]}"; do
            # Extract the chart name from the path
            chart_name=$(basename $path)
            
            # Only capture the first occurrence of 'version:' to ignore dependencies
            version=$(grep -m1 'version:' $path/Chart.yaml | awk '{print $2}')
            
            # Create the tag name by prepending the chart name and adding '-dev'
            tag="${chart_name}-${version}"

            # Configure git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # Delete existing tag if exists
            git tag -d $tag || true
            git push origin :refs/tags/$tag || true
            
            # Create and push new tag
            git tag $tag
            git push origin $tag
          done

      - uses: a-thomas-22/helm-push-action@v0.0.29
        env:
          PATHS: ${{ needs.get-modified-charts.outputs.paths }}
          FORCE: "True"
          CHARTMUSEUM_URL: "chartmuseum-external.iue1v1-0.i.arbitrum-internal.io/public"
          CHARTMUSEUM_ALIAS: "chartmuseum.offchainlabs.internal"
          CHARTMUSEUM_CA_CERT: "${{ secrets.CHARTMUSEUM_CA_CERT }}"
          CHARTMUSEUM_KEY: "${{ secrets.CHARTMUSEUM_KEY }}"
          CHARTMUSEUM_CERT: "${{ secrets.CHARTMUSEUM_CERT }}"
