name: Test Charts (Privileged)

on:
  workflow_run:
    workflows: ["Test Charts (Unprivileged)"]
    types:
      - completed

# Limit permissions to only what's needed
permissions:
  contents: read
  pull-requests: write  # Needed to comment on results

jobs:
  test-install:
    runs-on: ubuntu-latest
    # Only run if the unprivileged workflow completed successfully
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-info
          path: pr-info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Extract PR information
        id: extract-pr-info
        run: |
          echo "PR_NUMBER=$(cat pr-info/PR_NUMBER)" >> $GITHUB_ENV
          echo "HEAD_SHA=$(cat pr-info/HEAD_SHA)" >> $GITHUB_ENV
          echo "HAS_CHANGES=$(cat pr-info/HAS_CHANGES)" >> $GITHUB_ENV
          
          if [[ -f "pr-info/changed-charts.txt" ]]; then
            echo "CHANGED_CHARTS=$(cat pr-info/changed-charts.txt)" >> $GITHUB_ENV
          fi
      
      # Only proceed with testing if there are chart changes
      - name: Checkout repository
        if: env.HAS_CHANGES == 'true'
        uses: actions/checkout@v4
        with:
          # We're checking out the PR code, but we're not executing any untrusted code
          # We're only using it as a reference for chart-testing
          fetch-depth: 0
          ref: ${{ env.HEAD_SHA }}
          # Important: Don't persist credentials when checking out PR code
          persist-credentials: false
      
      - name: Set up Helm
        if: env.HAS_CHANGES == 'true'
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set up chart-testing
        if: env.HAS_CHANGES == 'true'
        uses: helm/chart-testing-action@v2.6.1

      - name: Create kind cluster
        if: env.HAS_CHANGES == 'true'
        uses: helm/kind-action@v1.9.0

      - name: Prepare CI secrets for Helm
        if: env.HAS_CHANGES == 'true'
        env:
          CI_TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.CI_TEST_ACCOUNT_PRIVATE_KEY }}
          CI_PARENT_CHAIN_URL_SEPOLIA: ${{ secrets.CI_PARENT_CHAIN_URL_SEPOLIA }}
          CI_BASELINE_RPC_KEY_SEPOLIA: ${{ secrets.CI_BASELINE_RPC_KEY_SEPOLIA }}
          CI_PARENT_CHAIN_BLOB_CLIENT_URL: ${{ secrets.CI_PARENT_CHAIN_BLOB_CLIENT_URL }}
          # Map additional secrets as needed
        run: |
          secrets_for_helm=""
          # Capture all 'CI_' prefixed environment variables into an array
          IFS=$'\n' read -r -d '' -a secret_names < <(env | grep '^CI_' | sed 's/=.*//' && printf '\0')
          
          for secret_name in "${secret_names[@]}"; do
            # Extract the variable name without the CI_ prefix for Helm values
            variable_name=$(echo $secret_name | sed 's/^CI_//')
            # Get the value of the dynamic variable name
            secret_value=${!secret_name}
            # Append to the secrets string in the required format
            if [ -z "$secrets_for_helm" ]; then
              secrets_for_helm="ci.secrets.${variable_name}=${secret_value}"
            else
              secrets_for_helm="${secrets_for_helm},ci.secrets.${variable_name}=${secret_value}"
            fi
          done
          
          # Remove the initial comma to clean up the format
          secrets_for_helm=${secrets_for_helm#,}
          
          # Format the entire string for --helm-extra-set-args, ensuring it's properly quoted
          helm_extra_set_args="--set ${secrets_for_helm}"

          # Use the command directly or set the HELM_EXTRA_SET_ARGS environment variable for later use in the workflow
          echo "HELM_EXTRA_SET_ARGS=${helm_extra_set_args}" >> $GITHUB_ENV
      
      - name: Run chart-testing (install)
        if: env.HAS_CHANGES == 'true'
        id: chart-test
        continue-on-error: true
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} --config ct.yaml --helm-extra-set-args "$HELM_EXTRA_SET_ARGS"
          echo "CT_EXIT_CODE=$?" >> $GITHUB_ENV
      
      - name: Determine test status
        id: test-status
        run: |
          if [[ "${{ env.HAS_CHANGES }}" == "false" ]]; then
            echo "STATUS=success" >> $GITHUB_ENV
            echo "STATUS_TEXT=No chart changes detected" >> $GITHUB_ENV
          elif [[ "${{ env.CT_EXIT_CODE }}" == "0" ]]; then
            echo "STATUS=success" >> $GITHUB_ENV
            echo "STATUS_TEXT=succeeded" >> $GITHUB_ENV
          else
            echo "STATUS=failure" >> $GITHUB_ENV
            echo "STATUS_TEXT=failed" >> $GITHUB_ENV
          fi
      
      - name: Update PR with test results
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr_number = process.env.PR_NUMBER;
            const commit_sha = process.env.HEAD_SHA;
            const status = process.env.STATUS;
            const status_text = process.env.STATUS_TEXT;
            
            const workflow_run_url = `https://github.com/${owner}/${repo}/actions/runs/${{ github.event.workflow_run.id }}`;
            const previous_run_url = `https://github.com/${owner}/${repo}/actions/runs/${{ github.event.workflow_run.id }}`;
            
            const status_icon = status === 'success' ? '✅' : '❌';
            
            let message = `## Chart Installation Test ${status_text} ${status_icon}
            
            The chart installation test for commit \`${commit_sha.substring(0, 7)}\` has ${status_text}.
            `;
            
            if (process.env.HAS_CHANGES === 'true') {
              message += `
            Changed charts: \`${process.env.CHANGED_CHARTS}\`
            `;
            }
            
            message += `
            [View workflow run](${workflow_run_url})
            [View unprivileged test run](${previous_run_url})
            
            ${status !== 'success' ? '⚠️ Please check the workflow logs for details on the failure.' : ''}`;
            
            try {
              // Find existing comment
              const { data: comments } = await github.rest.issues.listComments({
                owner,
                repo,
                issue_number: pr_number
              });
              
              const botComment = comments.find(comment => 
                comment.user.login === 'github-actions[bot]' && 
                comment.body.includes('Chart Installation Test')
              );
              
              if (botComment) {
                // Update existing comment
                await github.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: botComment.id,
                  body: message
                });
                console.log(`Updated existing comment #${botComment.id}`);
              } else {
                // Create new comment
                const { data: newComment } = await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pr_number,
                  body: message
                });
                console.log(`Created new comment #${newComment.id}`);
              }
            } catch (error) {
              console.error(`Error updating PR: ${error.message}`);
              core.setFailed(`Failed to update PR: ${error.message}`);
            }
